---
name: documentation
version: "1.0.0"
description: Comprehensive documentation generation and maintenance
author: Community
license: MIT
tags:
  - documentation
  - api
  - guides

requires:
  - claude-code: ">=1.0.0"

components:
  - type: commands
    path: commands/
  - type: agents
    path: agents/
  - type: mcp
    path: mcp/
  - type: templates
    path: templates/

config:
  auto_load: true
  enabled_by_default: true
---
